### ISSUE TITLE
False negative test results for checking typescript version compatability

### ISSUE THREAD

**Issue by jacobdr** [dcharbonnier/hydrated-ws#134]
I think that there are some issues with the test script introduced by #132, wherein we are getting no failure when in fact the case should fail

**Comment by jacobdr** [comment]
@dcharbonnier The branch is not ready to PR as I can clean it up a bunch more... but let me know if this errors out for you


```bash
git remote add jacobdr https://github.com/jacobdr/hydrated-ws.git
git checkout -b i134_ts_test_false_negative jacobr/i134_ts_test_false_negative
yarn
yarn run test-typescript-compatibility
```

**Comment by dcharbonnier** [comment]
The tests are working : https://travis-ci.org/dcharbonnier/hydrated-ws/jobs/451097635#L1489
As commented in #130 you are trying to compile the library with a different version of typescript instead of consuming it and I don't think you are supposed to do that, not with this library or any other library.

**Comment by dcharbonnier** [comment]
duplicate #130

**Comment by dcharbonnier** [comment]
I agree but on this specific case as you said the added information is not really interesting.
